config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-UserProfile:
      branch: master
      repo: https://github.com/athenarc/EOSCF-UserProfile
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-UserProfile git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-crimson-millipede.sh
        container: qc.acc_woolly-firebrick-seal
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-UserProfile find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-aqua-labradoodle.sh
        container: qc.doc_leaky-periwinkle-hornet
      github.com/athenarc/EOSCF-UserProfile git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-lavender-fish.sh
        container: qc.doc_squeaky-mustard-cheetah
      github.com/athenarc/EOSCF-UserProfile markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-pear-guppy.sh
        container: qc.doc_stinky-lime-bullfrog
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-UserProfile licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-puce-angelfish.sh
        container: qc.lic_sunny-chestnut-badger
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-UserProfile bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-sepia-hare.sh
        container: qc.sec_flimsy-ultramarine-mist
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-UserProfile flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cream-cat.sh
        container: qc.sty_squirrely-magnolia-crane
      github.com/athenarc/EOSCF-UserProfile hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-mustard-dugong.sh
        container: qc.sty_craggy-malachite-termite
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-UserProfile get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-seashell-spaniel.sh
        container: qc.ver_flabby-emerald-wolf
timeout: 5400
